export {
  type AiyokeExtension,
  type CapabilityPackExtension,
  type ContributionContext,
  type DetectionResult,
  defineFramework,
  defineLanguage,
  definePack,
  defineRuntime,
  defineTarget,
  EXTENSION_API_VERSION,
  type ExtensionDescriptor,
  type ExtensionDescriptorBase,
  type ExtensionKind,
  type ExtensionLoader,
  type ExtensionReference,
  type FrameworkExtension,
  type LanguageExtension,
  type RuntimeRenderContext,
  type RuntimeScope,
  type RuntimeTemplateExtension,
  type TargetExtension,
  type TargetRenderContext,
  type TargetVerificationContext,
  type WorkspaceSnapshot
} from "./contracts.js";
export { ExtensionRegistry } from "./registry.js";
