const descriptor = Object.freeze({
  kind: "target",
  id: "hello-target",
  version: "1.0.0",
  apiVersion: "1.0.0",
  displayName: "Hello target",
  description: "A complete external Aiyoke target example.",
  capabilities: ["instructions"],
  requires: [],
  conflicts: []
});

const extension = Object.freeze({
  descriptor,
  surface: "coding-agent",
  async render({ spec }) {
    return [
      {
        path: ".hello/AIYOKE.md",
        content: `# ${spec.project.name}\n\nGenerated by the external hello target.\n`,
        source: "hello-target",
        executable: false,
        ownership: "generated"
      }
    ];
  },
  async verify() {
    return [];
  }
});

export const loader = Object.freeze({
  descriptor,
  async load() {
    return extension;
  }
});
