import { generateKeyPairSync, sign } from "node:crypto";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { afterAll, describe, expect, it } from "vitest";
import { extensionId, type HarnessSpec } from "../../src/core/index.js";
import {
  manifestSigningPayload,
  runExtensionCompatibility,
  type SignedExtensionManifest,
  type TargetExtension
} from "../../src/extension-sdk/index.js";
import { renderSignedExtensionIsolated } from "../../src/index.js";
import {
  digestExtensionPackage,
  nodeManifestCrypto
} from "../../src/infrastructure/discovery/index.js";

const testDirectory = dirname(fileURLToPath(import.meta.url));
const exampleRoot = join(testDirectory, "../../examples/extensions/hello-target");
const temporaryRoots: string[] = [];

afterAll(async () => {
  await Promise.all(temporaryRoots.map((root) => rm(root, { recursive: true, force: true })));
});

const spec: HarnessSpec = {
  schemaVersion: 3,
  project: { name: "external-example", architecture: "layered" },
  composition: { kind: "single", stack: { languages: [], frameworks: [] } },
  runtime: { kind: "disabled" },
  targets: [],
  packs: [],
  generation: { sourceDirectory: ".aiyoke", lockFile: ".aiyoke/lock.json", lineEndings: "lf" }
};

const target = {
  kind: "coding-agent" as const,
  adapter: extensionId("hello-target"),
  features: ["instructions" as const],
  settings: {}
};

describe("external extension example", () => {
  it("passes the public compatibility kit and signed isolated rendering", async () => {
    const imported = (await import(pathToFileURL(join(exampleRoot, "package/index.mjs")).href)) as {
      readonly loader: {
        readonly descriptor: TargetExtension["descriptor"];
        load(): Promise<TargetExtension>;
      };
    };
    const compatibility = await runExtensionCompatibility({
      loader: imported.loader,
      fixture: {
        spec,
        target,
        modules: [],
        files: { "package.json": "{}" },
        secretCanaries: ["external-example-secret"]
      }
    });
    expect(compatibility.kind).toBe("passed");

    const root = await mkdtemp(join(tmpdir(), "aiyoke-external-example-"));
    temporaryRoots.push(root);
    const packageRoot = join(root, "package");
    await cp(join(exampleRoot, "package"), packageRoot, { recursive: true });
    const contentDigest = await digestExtensionPackage(packageRoot);
    const template = JSON.parse(
      await readFile(join(exampleRoot, "aiyoke-extension.template.json"), "utf8")
    ) as SignedExtensionManifest;
    const { publicKey, privateKey } = generateKeyPairSync("ed25519");
    const unsigned: SignedExtensionManifest = {
      ...template,
      content: { algorithm: "sha256", digest: contentDigest },
      signature: { algorithm: "ed25519", keyId: "external-example-test", value: "AA==" }
    };
    const payload = manifestSigningPayload(unsigned);
    const manifest: SignedExtensionManifest = {
      ...unsigned,
      signature: {
        ...unsigned.signature,
        value: sign(null, Buffer.from(payload, "utf8"), privateKey).toString("base64")
      }
    };
    const manifestPath = join(root, "aiyoke-extension.json");
    await writeFile(manifestPath, JSON.stringify(manifest), "utf8");
    const manifestDigest = nodeManifestCrypto.sha256(payload);
    const result = await renderSignedExtensionIsolated({
      manifestPath,
      packageRoot,
      trust: {
        roots: [
          {
            keyId: "external-example-test",
            publicKeyPem: publicKey.export({ type: "spki", format: "pem" }).toString()
          }
        ],
        revokedKeyIds: [],
        revokedContentDigests: [],
        revokedManifestDigests: []
      },
      consent: { kind: "granted", manifestDigest },
      invocation: {
        kind: "target-render",
        context: {
          spec,
          target,
          modules: [],
          workspace: {
            root: ".",
            files: ["package.json"],
            async read(path) {
              return path === "package.json" ? "{}" : undefined;
            },
            async exists(path) {
              return path === "package.json";
            }
          }
        }
      }
    });
    expect(result.kind).toBe("rendered");
    if (result.kind === "rendered") {
      expect(result.artifacts).toEqual([
        {
          path: ".hello/AIYOKE.md",
          content: "# external-example\n\nGenerated by the external hello target.\n",
          source: "hello-target",
          executable: false,
          ownership: "generated"
        }
      ]);
    }
  }, 20_000);
});
